### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by pingbee333** [jacobmstein/PlayerCountBot#7]
Hi, It drop me this error: 
Traceback (most recent call last):
  File "bot.py", line 27, in <module>
    client.run(config.BOT_TOKEN)
    
    I use python 3.6, help me :(

**Comment by jacobmstein** [comment]
Do you have a config file and do you have BOT_TOKEN defined?

**Comment by pingbee333** [comment]
yep, I have the token defined and I cloned the repository. I am trying to use the bot in replit (using python 3.6)

**Comment by jacobmstein** [comment]
I tried cloning this repo on [repl.it](https://repl.it) and was able to run the bot fine using `python3.6 bot.py`.
